### ISSUE TITLE
Encuestas post-charlas para obtener feedback

### ISSUE THREAD

**Issue by pabpercab1** [JaviFdez7/innosoft#24]
CUANDO SE COMENTE PARA PARTICIPAR DEBÉIS DECIR DESDE QUE COMITÉ VENÍS

NO TOCAR LOS TICKS, SOLO PERSONAS AUTORIZADAS

<h2>Comités necesarios:</h2>

- [x] Logística
- [ ] Igualdad
- [ ] Comunicación

<h2>Personas asignadas:</h2>
Logística:

- @antoniopelaezmoreno 
- @jaime-carbo 

Igualdad:

Comunicación:

**Comment by antoniopelaezmoreno** [comment]
Yo estoy interesado. Soy de logística

**Comment by jaime-carbo** [comment]
Estoy interesado y soy de logística. Mi uvus es jaicarsan1

**Comment by agudevbon** [comment]
Estoy interesado, soy de logística. Mi uvus es agudevbon.
